- name: "Install Node.js from Nodesource"
  become: true
  shell: |
    curl -sl https://deb.nodesource.com/setup_current.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs

- name: "Install Node.js 19"
  become: true
  apt:
    name: ["nodejs"]  
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    