---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install python3
  become: yes
  apt:
    name: python3


- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/web
    state: directory

- name: Copy index test page
  copy:
    src: "/home/circleci/project/artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Extract 
  ansible.builtin.unarchive:
    src: "/home/ubuntu/artifact.tar.gz"
    dest: "/home/ubuntu/web"
    remote_src: True

- name: install
  npm:
    name: install
    path: /home/ubuntu/web

- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/web/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
